version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/crud_dc/backend/static/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/crud_dc/backend/static/
    ports:
      - 5001:80
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume: